[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="notificationList" type="java.util.List<entities.Notification>" --]
[#-- @ftlroot "../resources/templates" --]
[#-- @ftlvariable name="friendList" type="java.util.List<entities.User>" --]
[#-- @ftlvariable name="postList" type="java.util.List<entities.Post>" --]
[#-- @ftlvariable name="wallOwner" type="entities.User" --]
[#-- @ftlvariable name="isFriend" type="boolean" file="templates/Wall/wall.ftl" --]
[#-- @ftlvariable name="suggestedFriendList" type="java.util.List<entities.User>" file="templates/Index/index.ftl" --]
[#-- @ftlvariable name="friendRequest" type="entities.FriendRequest" --]
[#-- @ftlvariable name="friendRequestList" type="java.util.List<FriendRequest>" file="templates/navbar.ftl" --]
[#-- @ftlvariable name="bodyBackground" type="java.lang.String" file="templates/base.ftl" --]
[#-- @ftlvariable name="loginRedirect" type="java.lang.String" file="templates/Auth/login.ftl" --]
[#-- @ftlvariable name="authenticationFailed" type="boolean" file="templates/Auth/login.ftl" --]
[#-- @ftlvariable name="authenticationSucceeded" type="java.lang.Boolean" file="templates/Auth/login.ftl" --]
[#-- @ftlvariable name="friendRequest" type="entities.FriendRequest" file="templates/Wall/wall.ftl" --]
[#-- @ftlvariable name="currentUser" type="entities.User" --]
[#-- @ftlvariable name="wallOwner.image" type="entities.Image" file="templates/Wall/wall.ftl" --]
[#-- @ftlvariable name="wallOwner" type="entities.User" file="templates/Wall/wall.ftl" --]
[#-- @ftlvariable name="friendList" type="java.util.List<User>" file="templates/Wall/friendList.ftl" --]
[#-- @ftlvariable name="friend" type="entities.User" file="templates/Wall/friendList.ftl" --]
