[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="isFriend" type="boolean" file="templates/Wall/wall.ftl" --]
[#-- @ftlvariable name="suggestedFriendList" type="java.util.List<User>" file="templates/Index/index.ftl" --]
[#-- @ftlvariable name="friendRequest" type="entities.FriendRequest" --]
[#-- @ftlvariable name="friendRequestList" type="java.util.List<FriendRequest>" file="templates/navbar.ftl" --]
[#-- @ftlvariable name="bodyBackground" type="java.lang.String" file="templates/base.ftl" --]
[#-- @ftlvariable name="loginRedirect" type="java.lang.String" file="templates/Auth/login.ftl" --]
[#-- @ftlvariable name="authenticationFailed" type="boolean" file="templates/Auth/login.ftl" --]
[#-- @ftlvariable name="authenticationSucceeded" type="java.lang.Boolean" file="templates/Auth/login.ftl" --]
[#-- @ftlvariable name="post.date" type="java.util.Date" file="templates/Wall/wall.ftl" --]
[#-- @ftlvariable name="post.image" type="entities.Image" file="templates/Wall/wall.ftl" --]
[#-- @ftlvariable name="post.user" type="entities.User" file="templates/Wall/wall.ftl" --]
[#-- @ftlvariable name="post.content" type="java.lang.String" file="templates/Wall/wall.ftl" --]
[#-- @ftlvariable name="postList" type="java.util.List<Post>" file="templates/Wall/wall.ftl" --]
[#-- @ftlvariable name="friendRequest" type="entities.FriendRequest" file="templates/Wall/wall.ftl" --]
[#-- @ftlvariable name="currentUser" type="entities.User" --]
[#-- @ftlvariable name="wallOwner.image" type="entities.Image" file="templates/Wall/wall.ftl" --]
[#-- @ftlvariable name="wallOwner" type="entities.User" file="templates/Wall/wall.ftl" --]
