
package util.soap.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SocialWebServiceService", targetNamespace = "http://ws.Soap.util/", wsdlLocation = "http://localhost:7777/ws/SocialWebService?wsdl")
public class SocialWebServiceService
    extends Service
{

    private final static URL SOCIALWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOCIALWEBSERVICESERVICE_EXCEPTION;
    private final static QName SOCIALWEBSERVICESERVICE_QNAME = new QName("http://ws.Soap.util/", "SocialWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/ws/SocialWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOCIALWEBSERVICESERVICE_WSDL_LOCATION = url;
        SOCIALWEBSERVICESERVICE_EXCEPTION = e;
    }

    public SocialWebServiceService() {
        super(__getWsdlLocation(), SOCIALWEBSERVICESERVICE_QNAME);
    }

    public SocialWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOCIALWEBSERVICESERVICE_QNAME, features);
    }

    public SocialWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SOCIALWEBSERVICESERVICE_QNAME);
    }

    public SocialWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOCIALWEBSERVICESERVICE_QNAME, features);
    }

    public SocialWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SocialWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SocialWebService
     */
    @WebEndpoint(name = "SocialWebServicePort")
    public SocialWebService getSocialWebServicePort() {
        return super.getPort(new QName("http://ws.Soap.util/", "SocialWebServicePort"), SocialWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SocialWebService
     */
    @WebEndpoint(name = "SocialWebServicePort")
    public SocialWebService getSocialWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.Soap.util/", "SocialWebServicePort"), SocialWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOCIALWEBSERVICESERVICE_EXCEPTION!= null) {
            throw SOCIALWEBSERVICESERVICE_EXCEPTION;
        }
        return SOCIALWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
